### ISSUE TITLE
Page number links not working

### ISSUE THREAD

**Issue by KyleBenson** [lotten/uci-thesis-latex#13]
The page numbers in e.g. the Table of Contents are not linking to the corresponding sections.  Any idea how to fix this?  Thank you!

**Comment by lotten** [comment]
Sorry I don't know. The section titles in the ToC are working hyperlinks. Should the page numbers also be links, i.e. is that the case for other pdfs you generated from latex?

From a quick look, the template simply imports the hyperref package [0] and later calls \tableofcontents [1]. Nothing special besides that from I can tell.
[0] https://github.com/lotten/uci-thesis-latex/blob/master/thesis.tex#L30
[1] https://github.com/lotten/uci-thesis-latex/blob/master/ucithesis.cls#L220

**Comment by KyleBenson** [comment]
I saw another thesis (that I think used this template) where the page numbers were also links.  But yes the section title links are working, although not on Overleaf for some reason.  Thanks!

**Comment by lotten** [comment]
FWIW, this might be relevant/related: https://tex.stackexchange.com/questions/238430/table-of-content-link-at-the-page-number-instead-of-the-section-body
